name: Development build

on:
  push:
    branches:
      - main
      - develop/*

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ gitea.workflow }}-${{ gitea.ref }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ gitea.ref_name }}
  GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx4g -XX:MaxMetaspaceSize=512m'"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need the tags to build
      - name: Setup
        uses: ./.gitea/actions/setup
      - name: Native build
        uses: ./.gitea/actions/native-build
        with:
          cache: true

      - name: Get version names
        run: |
          LATEST_TAG=$(git describe --tags --match 'v*' --abbrev=0)
          VERSION_NAME=$(git describe --tags --match 'v*' --long)
          if [[ $BRANCH_NAME == "main" ]]; then
            TAG_NAME="develop"
          else
            TAG_NAME="${BRANCH_NAME/\//-}"
          fi

          echo "LATEST_TAG=$LATEST_TAG" >> "$GITEA_ENV"
          echo "VERSION_NAME=$VERSION_NAME" >> "$GITEA_ENV"
          echo "TAG_NAME=$TAG_NAME" >> "$GITEA_ENV"
      - name: Build release app
        id: build
        env:
          KEY_ALIAS: "${{ secrets.KEY_ALIAS }}"
          KEY_PASSWORD: "${{ secrets.KEY_PASSWORD }}"
          KEY_STORE_PASSWORD: "${{ secrets.KEY_STORE_PASSWORD }}"
          SIGNING_KEY: "${{ secrets.SIGNING_KEY }}"
        run: |
          ./gradlew clean assembleRelease assembleDebug --no-daemon
      - name: Verify signatures
        run: |
          echo "Verify APK signatures"
          find app/build/outputs/apk -name '*.apk'
          find app/build/outputs/apk -name '*.apk' -print0 | xargs -t -0 -n1 ${{env.ANDROID_SDK_ROOT}}/build-tools/${{ env.BUILD_TOOLS_VERSION }}/apksigner verify --verbose --print-certs
      - name: Copy APK to shorter names
        id: apks
        run: |
          find app/build/outputs/apk -name '*.apk' -print0 |
            while IFS= read -r -d '' line; do
              # Halfin-release-0.3.4-2-62-g5c12e03-16-arm64-v8a.apk => Halfin-arm64-v8a.apk
              short_name="$(echo $line | sed -E 's/-[0-9]+\.[0-9]+\.[0-9]+-[0-9]+-g[a-fA-F0-9]+-[0-9]+//')"
              echo "$line => $short_name"
              cp "$line" "$short_name"
            done
          apks=$(find app/build/outputs/apk -name '*.apk' -print0 | tr '\0' ',' | sed 's/,$//')
          echo "apks=$apks" >> "$GITEA_OUTPUT"
      - name: Checksums
        run: |
          echo "SHA256 checksums:"
          find app/build/outputs/apk -name '*.apk' -print0 | xargs -0 sha256sum
      - name: Delete ${{ env.TAG_NAME }} tag and release
        env:
          GITEA_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # Note: Gitea CLI may differ from GitHub CLI
          # You may need to use Gitea API directly or gitea CLI if available
          # For now, we'll create the release using Gitea API
          API_URL="${{ gitea.server_url }}/api/v1"
          REPO="${{ gitea.repository }}"
          
          # Delete existing release if it exists
          curl -X DELETE \
            -H "Authorization: token $GITEA_TOKEN" \
            "$API_URL/repos/$REPO/releases/tags/${{ env.TAG_NAME }}" || true

          echo '### `${{ env.BRANCH_NAME }}` development build

This pre-release tracks the development build of Halfin from the `${{ env.BRANCH_NAME }}` unstable branch.

See https://git.hawke.one/Yogi/Halfin/releases/latest for the latest stable release.

If you want to update to this version in-app, change Settings->Advanced->Update URL to https://git.hawke.one/api/v1/repos/Yogi/Halfin/releases/tags/${{ env.TAG_NAME }}.

[See changes since `${{ env.LATEST_TAG }}`](https://git.hawke.one/Yogi/Halfin/compare/${{ env.LATEST_TAG }}...${{ env.TAG_NAME }})' > ci_release_note.txt

          # Create release using Gitea API
          # Note: This is a simplified version - you may need to adjust based on your Gitea version
          curl -X POST \
            -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"tag_name\": \"${{ env.TAG_NAME }}\",
              \"target_commitish\": \"${{ env.BRANCH_NAME }}\",
              \"name\": \"${{ env.VERSION_NAME }}\",
              \"body\": $(cat ci_release_note.txt | jq -Rs .),
              \"draft\": false,
              \"prerelease\": true
            }" \
            "$API_URL/repos/$REPO/releases"

          # Upload APKs to release (this may require additional API calls depending on Gitea version)

