name: Create release

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

env:
  APK_SHORT_NAME: Halfin.apk
  GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx4g -XX:MaxMetaspaceSize=512m'"
  TAG_NAME: ${{ gitea.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need the tags to build
      - name: Setup
        uses: ./.gitea/actions/setup
      - name: Native build
        uses: ./.gitea/actions/native-build
        with:
          cache: false
      - name: Build app
        id: buildapp
        env:
          KEY_ALIAS: "${{ secrets.KEY_ALIAS }}"
          KEY_PASSWORD: "${{ secrets.KEY_PASSWORD }}"
          KEY_STORE_PASSWORD: "${{ secrets.KEY_STORE_PASSWORD }}"
          SIGNING_KEY: "${{ secrets.SIGNING_KEY }}"
        run: |
          ./gradlew clean assembleRelease --no-daemon
      - name: Verify signatures
        run: |
          echo "Verify APK signatures"
          find app/build/outputs/apk -name '*.apk'
          find app/build/outputs/apk -name '*.apk' -print0 | xargs -0 -n1 ${{env.ANDROID_SDK_ROOT}}/build-tools/${{ env.BUILD_TOOLS_VERSION }}/apksigner verify --verbose --print-certs
      - name: Copy APK to shorter names
        id: apks
        run: |
          find app/build/outputs/apk -name '*.apk' -print0 |
            while IFS= read -r -d '' line; do
              # Halfin-release-0.3.4-2-62-g5c12e03-16-arm64-v8a.apk => Halfin-arm64-v8a.apk
              short_name="$(echo $line | sed -E 's/-release-[0-9]+\.[0-9]+\.[0-9]+-[0-9]+-g[a-fA-F0-9]+-[0-9]+//')"
              echo "$line => $short_name"
              cp "$line" "$short_name"
            done
          apks=$(find app/build/outputs/apk -name '*.apk' -print0 | tr '\0' ',' | sed 's/,$//')
          echo "apks=$apks" >> "$GITEA_OUTPUT"
      - name: Checksums
        run: |
          echo "SHA256 checksums:"
          find app/build/outputs/apk -name '*.apk' -print0 | xargs -0 sha256sum
      - name: Create Gitea release
        env:
          GITEA_TOKEN: ${{ secrets.TOKEN }}
        run: |
          API_URL="${{ gitea.server_url }}/api/v1"
          REPO="${{ gitea.repository }}"
          
          # Create release using Gitea API
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"tag_name\": \"${{ env.TAG_NAME }}\",
              \"target_commitish\": \"${{ gitea.sha }}\",
              \"name\": \"${{ env.TAG_NAME }}\",
              \"body\": \"Halfin release ${{ env.TAG_NAME }}\",
              \"draft\": false,
              \"prerelease\": false
            }" \
            "$API_URL/repos/$REPO/releases")
          
          # Extract release ID from response (adjust based on Gitea API version)
          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id // empty')
          
          if [ -z "$RELEASE_ID" ]; then
            echo "Failed to create release or extract release ID"
            echo "Response: $RELEASE_RESPONSE"
            exit 1
          fi
          
          # Upload APKs to release
          for apk in app/build/outputs/apk/**/*.apk; do
            if [ -f "$apk" ]; then
              FILENAME=$(basename "$apk")
              curl -X POST \
                -H "Authorization: token $GITEA_TOKEN" \
                -F "attachment=@$apk" \
                "$API_URL/repos/$REPO/releases/$RELEASE_ID/assets?name=$FILENAME"
            fi
          done

